version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=file-sharing-app
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  client:
    build:
      context: ./packages/client
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - PORT=${FRONTEND_PORT}
      - VITE_CLIENT_URL=${VITE_CLIENT_URL}
      - NX_PUBLIC_API_URL=${NX_PUBLIC_API_URL}
      - BACKEND_PORT=${BACKEND_PORT}

  api:
    build:
      context: ./packages/api
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - PORT=${BACKEND_PORT}
      - VITE_CLIENT_URL=${VITE_CLIENT_URL}
      - NX_PUBLIC_API_URL=${NX_PUBLIC_API_URL}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongodb

volumes:
  mongodb_data:
